### ISSUE TITLE
[FEATURE] Bed Aura

### ISSUE THREAD

**Issue by Tigermouthbear** [AresClient/ares#14]
**What version is this applicable?**
both

**Description and explanation of new feature**
Placing beds in the nether makes a big explosion, this can be used instead of crystals. Its especially effective in 1.16

**Additional context**
I'll be working on this unless someone else wants to give it a try

**Comment by etechic** [comment]
This would be nice

**Comment by ghost** [comment]
This is a feature now right? If so, I think we should close this issue.

**Comment by Tigermouthbear** [comment]
it's not a feature yet

**Comment by Doogie13** [comment]
1.12.2 placements on the 1.12.2 version planned?

**Comment by ghost** [comment]
This is now a feature on both Forge and Fabric, please close.
