### ISSUE TITLE
[BUG] GL Error, 1281

### ISSUE THREAD

**Issue by IUDevman** [AresClient/ares#20]
**What version is this applicable?**
Forge

**Describe the bug**
The minecraft output log is flooded with OpenGL errors when the panel GUI is extended.

**To Reproduce**
1. Launch latest dev build of Ares Forge
2. Open ClickGUI
3. Enable panel GUI and extend one of the panels.

_**The GL error only occurs with the panel GUI and with an extended panel**_

**Additional context**
- Builds tested on Forge 1.12.2-14.23.5.2835

This is the exact error that is printed in the game output:
```
[Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[Client thread/ERROR] [minecraft/Minecraft]: 1281: Invalid value
```

**Comment by Makrennel** [comment]
I've noticed this before, happens with Fabric version too, output in console:

`[Thread-102/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. Width and height must not be negative.`

**Comment by Tigermouthbear** [comment]
for future reference, this error was caused by a negative scissor height
