### ISSUE TITLE
[FEATURE] AutoTool

### ISSUE THREAD

**Issue by Kore-Development** [AresClient/ares#21]
**What version is this applicable?**
both

**Description and explanation of new feature**
AutoTool

**Additional context**
Like from Impact

**Comment by Tigermouthbear** [comment]
this is already in both versions

**Comment by Kore-Development** [comment]
where is it?

**Comment by Kore-Development** [comment]
i couldnt find it

**Comment by Tigermouthbear** [comment]
oh, I guess it's only on the 1.12.2 version. I'll port it to 1.16.4

**Comment by Kore-Development** [comment]
#23

**Comment by Tigermouthbear** [comment]
I'm closing this issue, #23 will replace it
