### ISSUE TITLE
[FEATURE] local chunks cache

### ISSUE THREAD

**Issue by Dejniel** [AresClient/ares#26]
** What version is this applicable? **
botch

** Description and explanation of new feature **
Is they any way to add chunks cache?
I mean...
Holding the map locally downloaded from active chunks or taken from generator

I would like to increase render distance even if far chunks will be out-of-date
I cannot find any information about this feature other than https://feedback.minecraft.net/hc/en-us/community/posts/360070251892-Add-Client-Chunk-Cache
It will be unique
It should also be very helpful in finding distant players activities
** Additional context **
Is it a lot of work? 
Are there technological barriers? 
I'm senior java dev and i can implement it but i need some introduction as i don't have enough time to get in this technology for myself

**Comment by Tigermouthbear** [comment]
I feel that this is out of the scope of the client's goals rn, I can accept a PR if you would like to add this yourself.
