### ISSUE TITLE
Porting Forge modules to Fabric

### ISSUE THREAD

**Issue by Tigermouthbear** [AresClient/ares#3]
## Overview
Currently the fabric version is lacking on modules, especially combat ones. This issue is a list of all modules which have a forge equivalent. Meaning, it should be relatively easy to port them to fabric.

## Modules to port
- [x] BoatFly
- [x] CrystalAura
- [x] AutoSurround
- [x] AutoTrap
- [x] HoleFiller

- [x] Offhand
- [x] OffhandGap
- [x] Surround
- [x] TotemPopCounter
- [x] NoSwing
- [x] PacketCancel
- [x] LiquidInteract

- [x] MultiTask
- [x] EntitySpeed
- [x] IceSpeed
- [x] AntiHitbox
- [x] AutoReconnect
- [x] DebugCrosshair
- [x] NoForceLook
- [x] Scaffold
- [x] MapTooltips
- [x] NoFog
- [x] VisualRange
- [x] Trajectories

## Contributing
If you would like to help, please comment which modules you will or are working on below. This checklist will be updated as the modules are completed.

**Comment by IUDevman** [comment]
I'm planning on porting:
TotemPopCounter
NoSwing
AntiHitbox

Finished with TotemPopCounter, once I get the other two done I'll make a pull request.

**Comment by Tigermouthbear** [comment]
great, I'm working on surround, crystalaura, and offhand right now

**Comment by Tigermouthbear** [comment]
all modules that can be are ported to fabric now

**Comment by Kore-Development** [comment]
#21 is missing unless this can't be ported

**Comment by Tigermouthbear** [comment]
You moved it to #23 along with the other modules missing in fabric
