### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by master7720** [AresClient/ares#40]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (Ares-2.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/30/21 12:36 AM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.j
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$288/759933344.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zbn000(Minecraft.java)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1755)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.j.a(Unknown Source)
	at baritone.j.onTick(Unknown Source)
	at baritone.cf.a(Unknown Source)
	at baritone.cf$$Lambda$288/759933344.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.cf.onTick(Unknown Source)
	at net.minecraft.client.Minecraft.handler$runTick$zbn000(Minecraft.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PreparedSystem32'/237, l='MpServer', x=224.43, y=69.00, z=351.05]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 711836 game time, 354346 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 29 total; [EntityParrot['Parrot'/132, l='MpServer', x=274.41, y=65.00, z=301.75], EntityOcelot['Ocelot'/68, l='MpServer', x=156.50, y=72.00, z=302.69], EntitySheep['Sheep'/133, l='MpServer', x=281.45, y=62.00, z=309.45], EntitySheep['Sheep'/69, l='MpServer', x=152.61, y=72.00, z=307.80], EntityOcelot['Ocelot'/70, l='MpServer', x=147.22, y=66.00, z=334.51], EntityBat['Bat'/71, l='MpServer', x=151.75, y=27.00, z=399.75], EntityBat['Bat'/72, l='MpServer', x=153.67, y=27.62, z=392.74], EntityBat['Bat'/73, l='MpServer', x=153.47, y=21.00, z=392.75], EntityBat['Bat'/74, l='MpServer', x=163.15, y=23.72, z=399.31], EntityWolf['Wolf'/143, l='MpServer', x=302.73, y=64.00, z=317.39], EntityPlayerSP['PreparedSystem32'/237, l='MpServer', x=224.43, y=69.00, z=351.05], EntityCow['Cow'/81, l='MpServer', x=171.60, y=71.00, z=300.80], EntityBat['Bat'/82, l='MpServer', x=169.25, y=20.62, z=405.08], EntityBat['Bat'/83, l='MpServer', x=183.82, y=18.93, z=410.22], EntityBat['Bat'/84, l='MpServer', x=177.59, y=20.49, z=406.06], EntityBat['Bat'/85, l='MpServer', x=165.21, y=38.34, z=424.40], EntityBat['Bat'/89, l='MpServer', x=183.21, y=52.05, z=293.45], EntityOcelot['Ocelot'/90, l='MpServer', x=178.55, y=73.00, z=312.22], EntitySquid['Squid'/101, l='MpServer', x=215.23, y=60.36, z=311.85], EntitySheep['Sheep'/108, l='MpServer', x=238.77, y=68.00, z=280.52], EntityBat['Bat'/109, l='MpServer', x=232.20, y=16.10, z=342.01], EntitySquid['Squid'/110, l='MpServer', x=235.40, y=60.43, z=390.20], EntityOcelot['Ocelot'/116, l='MpServer', x=249.50, y=69.00, z=346.72], EntityOcelot['Ocelot'/122, l='MpServer', x=260.73, y=66.00, z=286.68], EntityOcelot['Ocelot'/123, l='MpServer', x=261.25, y=65.00, z=306.50], EntityOcelot['Ocelot'/124, l='MpServer', x=267.70, y=67.00, z=353.51], EntityOcelot['Ocelot'/125, l='MpServer', x=264.30, y=69.00, z=354.70], EntityOcelot['Ocelot'/126, l='MpServer', x=257.52, y=70.00, z=358.65], EntityOcelot['Ocelot'/127, l='MpServer', x=267.77, y=68.00, z=368.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 295822368 bytes (282 MB) / 704643072 bytes (672 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G6_pre1 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ares      | 2.8          | Ares-2.8-1.12.2.jar           | None                                     |

	Loaded coremods (and transformers): 
MixinLoader (Ares-2.8-1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5058' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.4.0 - Build 20.19.15.5058, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, Fabric Mods, file/Mypack_2.2.1.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.5058
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Tigermouthbear** [comment]
I'm pretty sure this is a noverify issue, please try disabling -noverify by removing it from your jvm args

**Comment by master7720** [comment]
okk

**Comment by Tigermouthbear** [comment]
does it work for you now?

**Comment by master7720** [comment]
yes
