### ISSUE TITLE
how do i build the client

### ISSUE THREAD

**Issue by master7720** [AresClient/ares#44]
i want to build the 1.12.2 folder but its weird too

**Comment by Tigermouthbear** [comment]
run `gradlew build` or `gradlew :ares-forge:build` in the main folder of the project. see the README.md for more  info.

**Comment by master7720** [comment]
this makes senses

**Comment by master7720** [comment]
yea i did all of that still didnt work

**Comment by Tigermouthbear** [comment]
what isn't working? Can you give me a log?

**Comment by master7720** [comment]
* Where:
Build file 'C:\Users\User\Desktop\ares\ares-fabric\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.8-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Java (8). Java 16 or higher is required.
     The JAVA_HOME environment variable is currently set to (C:\Program Files\Java\jdk1.8.0_291).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Tigermouthbear** [comment]
you need to use JDK 17 to build this client

**Comment by master7720** [comment]
i have jdk 8 and 17 installed

**Comment by ghost** [comment]
set your JAVA_HOME environment variable to your jdk 17 path

**Comment by Tigermouthbear** [comment]
closing this, please use JDK 17
