### ISSUE TITLE
[BUG] don't take fall damage

### ISSUE THREAD

**Issue by pikacan360** [AresClient/ares#57]
**What version is this applicable?**
Forge Ares 2.9

**Describe the bug**
Even thought there isn't a toggleable nofall module, you don't take fall damage

**To Reproduce**
just load up the client and jump off a cliff, Idk if you will or not though

**Screenshots**
You can't take a screenshot of not taking damage but here's a video
https://youtu.be/6-wB0fFtl94

**Additional context**
The reason the textures in the video are the new textures and not the old ones is cause I am using a texture pack

**Comment by Tigermouthbear** [comment]
This is a side effect of the AntiHunger module. I will try to eliminate this side effect while we rewrite ares (the 3.0/mesh branch is where development for ares is currently happening).
