### ISSUE TITLE
[BUG] InventoryMove

### ISSUE THREAD

**Issue by IUDevman** [AresClient/ares#6]
**What version is this applicable?**
Fabric 1.16.4, latest build from the master branch.

**Describe the bug**
On the latest build for fabric, gui screens such as the clickgui, escape screen, chat, and inventory disappear if you have inventorymove enabled and you respawn.

**To Reproduce**
Fabric version used: fabric-loader-0.10.6+build.214-1.16.4
Server tested on: Endcrystal.me

* Enable InventoryMove module, at this point everything will work fine.
* die by /kill
* Once respawned, open a gui screen and it disappears. After this, all gui screens will appear invisible.

**Additional context**
No other mods were loaded in fabric.

**Comment by Tigermouthbear** [comment]
This is very strange, it seems to go away when you walk aways a bit. Heres a strange error too: https://i.aresclient.org/ki3x0bza.txt

**Comment by Tigermouthbear** [comment]
turns out it was a bug with chest esp
